apiVersion: v2
description: Web service to allow registration of owned dangerous dogs
name: dangerous-dogs-act
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 3.4.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
