environment: production
environmentCode:
name: dangerous-dogs-act
namespace: dangerous-dogs
workstream: dangerous-dogs
image: dangerous-dogs-act

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: dangerous-dogs-act-config-map

containerSecret:
  name: dangerous-dogs-act-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

ingress:
  class: nginx
  endpoint: dangerous-dogs-act
  server: value.replaced.from.app.config

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
