{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-register.config-map") -}}
{{- define "aphw-ddi-register.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  {{- if .Values.pr }}
  REDIS_PARTITION: {{ .Values.container.redisPartition }}-{{ .Values.pr }}
  {{ else }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  OS_PLACES_API_KEY: {{ quote .Values.container.osPlacesApiKey }}
  PAYMENT_ENABLED: {{ quote .Values.container.paymentEnabled }}
  PAYMENT_VALUE: {{ quote .Values.container.paymentValue }}
  PAYMENT_API_URL: {{ quote .Values.container.paymentApiUrl }}
  PAYMENT_API_KEY: {{ quote .Values.container.paymentApiKey }}
  PAYMENT_RETURN_URL: {{ quote .Values.container.paymentReturnUrl }}
  SERVICE_URI: {{ quote .Values.container.serviceUri }}

{{- end -}}
