services:
  aphw-ddi-register:
    build:
      context: .
      target: production
    image: aphw-ddi-register
    container_name: aphw-ddi-register
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-register-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://aphw-ddi-register-azurite:10002/devstoreaccount1;
      AZURE_STORAGE_ACCOUNT_NAME: devstoreaccount1
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-test}
      PAYMENT_API_URL: ${PAYMENT_API_URL:-https://publicapi.payments.service.gov.uk/v1/payments}
      PAYMENT_API_KEY:
      PAYMENT_RETURN_URL: ${PAYMENT_RETURN_URL:-http://localhost:3000/register/payment-return}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-test}

  aphw-ddi-register-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose"
    labels:
      com.docker.compose.aphw.ddi.register.role: aphw-ddi-register-azurite
