# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  aphw-ddi-register:
    build:
      target: development
    image: aphw-ddi-register-development
    container_name: aphw-ddi-register-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json

  aphw-ddi-register-azurite:
    labels:
      com.docker.compose.aphw.ddi.register.role: test
