services:
  dangerous-dogs-act-reg-web:
    build:
      context: .
      target: production
    image: dangerous-dogs-act-reg-web
    container_name: dangerous-dogs-act-reg-web
    environment:
      APPINSIGHTS_CLOUDROLE: dangerous-dogs-act-reg-web-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
