services:
  dangerous-dogs-act:
    build:
      context: .
      target: production
    image: dangerous-dogs-act
    container_name: dangerous-dogs-act
    environment:
      APPINSIGHTS_CLOUDROLE: dangerous-dogs-act-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
