environment: production
environmentCode:
name: aphw-ddi-register
namespace: ffc-techspike
workstream: aphw-ddi
image: aphw-ddi-register

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: aphw-ddi-register-config-map

containerSecret:
  name: aphw-ddi-register-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  imagePullPolicy: IfNotPresent
  redisHostname: redis-hostname.default
  redisPartition: aphw-ddi-register
  redisPassword: redis
  redisPort: 6379
  notifyApiKey: notify-api-key
  osPlacesApiKey: os-places-api-key
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageAccountName: aphwddi

ingress:
  class: nginx
  endpoint: aphw-ddi-register
  server: value.replaced.from.app.config

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
